### ISSUE TITLE
Custom LOCAL_DOMAIN instance setting isn't considered

### ISSUE THREAD

**Issue by ruario** [raikasdev/mastopoet#11]
Some instances (e.g. social.vivaldi.net or mastodon.elevenways.be) have a LOCAL_DOMAIN has been set to just to a sub part of the domain (e.g. vivaldi.net), while WEB_DOMAIN is set to the complete domain (e.g. social.vivaldi.net)
mastopoet doesn't seem to use this, and just shows the full address.

Mastopoet image:
![image](https://github.com/raikasdev/mastopoet/assets/7015074/2a0ab8ec-14c1-4bce-85bf-3d3aab4fa241)

Screenshot from the instance directly:
![image](https://github.com/raikasdev/mastopoet/assets/7015074/d5e8ced8-206d-4297-b716-97d64c55e822)

Note the difference in username. Mastopoet shows @​atlemo​@​social.vivaldi.net (which is not correct), while it should be @​atlemo​@​vivaldi.net .

**Comment by raikasdev** [comment]
Yep, I would need to do WebFinger lookups for that, as the API doesn't provide the instance name straight on (on the local server).
