### ISSUE TITLE
Suggestion: Add button to copy post text for Alt text

### ISSUE THREAD

**Issue by aaaaalbert** [raikasdev/mastopoet#12]
Hi, I just learned about this nice tool of yours! The [post I read pointing to it](https://mementomori.social/@rolle/110787810442832467) goes on to suggest that one should "remember to copy the post text as alt text".

Mastopoet could make that easy for the user by **providing a "Copy alt text" button** right next to the "Download .png" button like so:

![image](https://github.com/raikasdev/mastopoet/assets/3806695/5a1c9d4f-9c53-4e92-bbb8-b294718ae5c5)

**Comment by raikasdev** [comment]
Implemented in [00ccc1e](https://github.com/raikasdev/mastopoet/commit/00ccc1e0548d72465d164b6be0c94fc28d70b2ec)

**Comment by aaaaalbert** [comment]
Wow, that was fast! Thank you! :rocket:
