### ISSUE TITLE
Mastodon (Dark) output file missing feed icons

### ISSUE THREAD

**Issue by hybridhavoc** [raikasdev/mastopoet#19]
When choosing the Mastodon (Dark) theme and leaving everything else the same, the resulting file does not have the feed icons.

Sample post URLs: 
https://mementomori.social/@raikas/110791964284177557
https://beige.party/@RickiTarr/110793825177470796
![mastopoet-RickiTarr-28072023](https://github.com/raikasdev/mastopoet/assets/53440374/d281eed6-c704-4051-afa2-713d4d680f45)
![mastopoet-raikas-28072023](https://github.com/raikasdev/mastopoet/assets/53440374/3996e1d1-8693-4997-9614-12ad68825dd4)

**Comment by raikasdev** [comment]
This has been now fixed! It was due to the icon's SVGs in the data uri's having widths, so html2canvas couldn't figure out their width, and figured it was 0.
