### ISSUE TITLE
Background resizing is glitchy with bottom-center and top-center handles

### ISSUE THREAD

**Issue by Eldemarkki** [raikasdev/mastopoet#20]
When resizing from the bottom-center handle, the height of the background "flickers" before stabilizing. The same happens when resizing with the top-center handle, but is less noticeable. Didn't notice any problems with the other resizing handles.

This was recorded on Firefox 115.0.2, but I noticed the same on Chrome:
![Peek 2023-07-29 14-20](https://github.com/raikasdev/mastopoet/assets/38920928/9b56cefb-e6d7-40b9-ba33-b45933ec427e)

**Comment by raikasdev** [comment]
Fixed in release 1.0.1
