### ISSUE TITLE
[Feature Request] alt text in other languages

### ISSUE THREAD

**Issue by jze** [raikasdev/mastopoet#22]
It would be very nice if the alt-text could be generated in other languages as well.

I will be happy to help with the translation into German. Here already a few text snippets:

*Ein Bildschirmfoto eines Beitrags von … verschönert mit der Software Mastopoet. Es wurde am … veröffentlicht und hat 2 Favoriten, 3 Boots und 5 Antworten.*

*Der Beitrag hat einen Anhang. Der Anhang hat keinen Alternativtext.*

*Der Beitrag hat einen Anhang. Der Alternativtext des Anhangs lautet:*

**Comment by raikasdev** [comment]
Danke schön! I'll try to add that soon.
