### ISSUE TITLE
Date seems to maybe always show as July 28th

### ISSUE THREAD

**Issue by hybridhavoc** [raikasdev/mastopoet#29]
It seems like the date in the resulting file may always show as July 28th.

Created today:
![mastopoet-Rand__alThor-08082023](https://github.com/raikasdev/mastopoet/assets/53440374/9e399ad1-6139-4f95-a839-22ffffd00e38)
From [this post](https://darkfriend.social/@Rand__alThor/110856899581413318).

Created July 29th:
![mastopoet-HumanServitor-29072023](https://github.com/raikasdev/mastopoet/assets/53440374/092bcda6-b814-4a78-b111-23e647f6491a)

**Comment by raikasdev** [comment]
Forgot to fix the date formatting from debug in that position also. Fixed.
