### ISSUE TITLE
Idea : Automatically add alt text in metadata of the image

### ISSUE THREAD

**Issue by Cqoicebordel** [raikasdev/mastopoet#37]
There is a tag in Exif for Image description (tag ID 0x010e).

It could be interesting to add the alt text in that part of the JPG when downloading it, so it couldn't be separated from it's alt text.

**Comment by raikasdev** [comment]
Mastodon doesn't support getting alt text automatically from the description sadly, but platforms like WordPress do. Will have to investigate if this is doable using the Canvas API.

**Comment by Cqoicebordel** [comment]
Yeah, my idea was following the discussion on Masto : have a news article include a post quasi-automatically. If they add the reading of the Exif description, it could be done quite easily for them.
