### ISSUE TITLE
Idea : Provide a REST API

### ISSUE THREAD

**Issue by Cqoicebordel** [raikasdev/mastopoet#38]
The UX for using Mastopoet isn't ideal : copy the link, open a new tab, open Mastopoet, paste the link, set the settings, download the image, integrate the image.

A few step could be eliminated if a request to an URL like `https://mastopoet.raikas.dev/?link=mastodon.social/XXXXX&theme=bird&margin=10…` could return a JPG directly.  
This way, that kind of link could be integrated directly into other sites as well, using the URL as an `src` in an `<img>` tag, or just used as a bookmarklet.

Using issue #37, the alt text could be integrated in the file directly, to smooth the integration into other sites (if they handle the Exif tag). Or, another parameter could be added (`&alt` or `&image`)

Cons : if it is used a lot, Mastopoet might become overloaded.

**Comment by raikasdev** [comment]
Mastopoet currently is a SPA app, meaning it's doing everything on the clients browser. So getting a direct JPG from an URL isn't currently possible, without having to write a seperate API.

Also, Mastopoet currently supports the `?url=https://mastodon.social/@abcd/00000` query tag, so you can use a bookmarklet:

```js
javascript:(()=>{window.open(`https://mastopoet.raikas.dev?url=${window.location.toString()}`);})();
```

Just select that and drag it to your bookmarks bar and name it "Mastopoet". Or just copy it, go to "Bookmarks" and create a new bookmark in your browser, and set the URL to that.

**But:** it would be possible to create an embeddable iframe, like Twitter has.

**Comment by Cqoicebordel** [comment]
> But: it would be possible to create an embeddable iframe, like Twitter has.

Oh ! That could be very interesting indeed, especially if all is done in the client side !

**Comment by raikasdev** [comment]
Wrong one.

**Comment by Cqoicebordel** [comment]
I am in awe of your speed, and the quality of the work.

Kudos !
