### ISSUE TITLE
Symbol.replace issue

### ISSUE THREAD

**Issue by hybridhavoc** [raikasdev/mastopoet#39]
It appears that mastopoet may be struggling with a certain symbol.  Mastodon post in question is at https://mastodon.world/@MonotoneofBill/111255575208426695

Display name is: M❍n❍t❍ne❍fBill™

When attempting to download the .jpg console shows:
```
index-05e80653.js:79 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at index-05e80653.js:79:36934
    at [Symbol.replace] (<anonymous>)
    at String.replaceAll (<anonymous>)
    at index-05e80653.js:79:36877
```

**Comment by raikasdev** [comment]
This is now fixed, BUT I strongly recommend you remove those emojis from your username. They are bad for accessibility.
