### ISSUE TITLE
Really long URLs should be handled differently

### ISSUE THREAD

**Issue by QWxleA** [raikasdev/mastopoet#6]
The tools is very nice, but long urls (or possibly words, what if somebody from Taumatawhakatangihangakoauauotamateaturipukakapiki-maungahoronukupokaiwhenuakitnatahu starts using Mastodon?) should either be cut of using elipses (...), or broken over two lines.

<img width="933" alt="image" src="https://github.com/raikasdev/mastopoet/assets/24763887/d0cb29b6-f0c6-4ed2-b113-7d837a09613a">

Besides that, kudos!

**Comment by raikasdev** [comment]
Hmm, thats weird! It seems to be working just fine on my end. What browser are you using?
![image](https://github.com/raikasdev/mastopoet/assets/29684625/7de19e33-7b7f-4453-83c4-fc6c1fc9af54)

**Comment by QWxleA** [comment]
Mona, on Mac, let me try some others as well

**Comment by raikasdev** [comment]
Fixed! Didn't realize the API also returned those "invisible"-classed spans (for screen readers). Now the links should work fine!
